package com.toptal.tests;
// Generated by Selenium IDE
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.WebDriver;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.junit.jupiter.api.extension.ExtendWith;
import io.github.bonigarcia.seljup.SeleniumJupiter;
import com.toptal.webpages.HomePage;
import com.toptal.webpages.DeveloperApplyPage;
import java.util.concurrent.TimeUnit;

@ExtendWith(SeleniumJupiter.class)
public class ApplyAsAFreelancerTest {

  private WebDriver driver;

  public ApplyAsAFreelancerTest(FirefoxDriver driver) {this.driver = driver;}

  @BeforeEach
  public void setup(){
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.manage().deleteAllCookies();
    driver.manage().window().maximize();
  }

  @AfterEach
  public void tearDown(){

  }

  @Test
  public void applyAsAFreelancer(FirefoxDriver driver) {
    //Create object of HomePage Class
    HomePage home = new HomePage(driver);
    assertTrue(home.isPageOpened());
    home.clickOnDeveloperApplyButton();

    //Create object of DeveloperApplyPage
    DeveloperApplyPage applyPage =new DeveloperApplyPage(driver);

    //Check if page is opened
    assertTrue(applyPage.isPageOpened());

    //Fill up data
    applyPage.setDeveloper_email("ricardo.cruz29@ua.pt ");
    applyPage.setDeveloper_full_name("Ricardo Saraiva da Cruz");
    applyPage.setDeveloper_password("123456789");
    applyPage.setDeveloper_password_confirmation("123456789");

    //Click on join
    //applyPage.clickOnJoin();
  }
}
