pipeline {
  agent any
  tools {
      jdk 'jdk11'
      maven 'maven'
  }
  stages {
      stage('Install') {
          steps {
              sh 'mvn clean install'               
          }
      }
      psot {
      	always {
      		junit '**/target/*-reports/TEST-*.xml'
      	}
      }
      
  }
}

