package SampleTest;
// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class BlazeTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach

  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/home/ricardo/Desktop/TQS/TQS/Lab3/geckodriver");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void blazeTest() {
    driver.get("https://blazedemo.com/");

    driver.manage().window().setSize(new Dimension(824, 693));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Boston']")).click();
    }
    driver.findElement(By.cssSelector(".form-inline:nth-child(1) > option:nth-child(3)")).click();
    {
      String value = driver.findElement(By.name("fromPort")).getAttribute("value");
      assertThat(value, is("Boston"));
    }
    assertThat(driver.findElement(By.name("fromPort")).getText(), is("Paris\nPhiladelphia\nBoston\nPortland\nSan Diego\nMexico City\nSão Paolo"));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Portland']")).click();
    }
    driver.findElement(By.cssSelector(".form-inline:nth-child(1) > option:nth-child(4)")).click();
    {
      String value = driver.findElement(By.name("fromPort")).getAttribute("value");
      assertThat(value, is("Portland"));
    }
    assertThat(driver.findElement(By.name("fromPort")).getText(), is("Paris\nPhiladelphia\nBoston\nPortland\nSan Diego\nMexico City\nSão Paolo"));
    assertThat(driver.getTitle(), is("BlazeDemo"));
    assertThat(driver.getTitle(), is("BlazeDemo"));
    driver.findElement(By.cssSelector(".btn-primary")).click();


    driver.findElement(By.cssSelector("tbody > tr:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(7)")).getText(), is("$472.56"));
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();
    driver.findElement(By.cssSelector("p:nth-child(7)")).click();
    assertThat(driver.findElement(By.cssSelector("em")).getText(), is("914.76"));
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.cssSelector(".control-group:nth-child(11) > .control-label")).click();
    driver.findElement(By.id("nameOnCard")).click();
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Aveiro");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.getTitle(), is("BlazeDemo Confirmation"));
    driver.findElement(By.cssSelector(".hero-unit")).click();
    assertThat(driver.getTitle(), is("BlazeDemo Confirmation"));
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Thank you for your purchase today!"));
  }
}
