package ptua.airqualityAPI.WebApp;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.junit.jupiter.api.extension.ExtendWith;
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

@ExtendWith(SeleniumJupiter.class)
public class AirQualityTest {
  @Test
  public void airQualityTest(FirefoxDriver driver) throws InterruptedException {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1848, 1053));
    driver.findElement(By.cssSelector("#air h6")).click();
    driver.findElement(By.cssSelector(".air-title")).click();
    driver.findElement(By.cssSelector("#city path")).click();
    driver.findElement(By.id("city-choose")).click();
    {
      WebElement dropdown = driver.findElement(By.id("city-choose"));
      dropdown.findElement(By.xpath("//option[. = 'Paris']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(8)")).click();
    driver.findElement(By.cssSelector(".search-button")).click();

    WebDriverWait wait = new WebDriverWait(driver, 60);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".results-section > h6")));

    assertThat(driver.findElement(By.cssSelector(".results-section > h6")).getText(), is("Results for city Paris"));
    driver.findElement(By.cssSelector("#results-co > h3")).click();
    assertThat(driver.findElement(By.cssSelector("#results-no2 > h2")).getText(), is("NO2"));
    driver.findElement(By.cssSelector("#results-no2 > h3")).click();

    driver.findElement(By.cssSelector("#lat-long svg")).click();
    driver.findElement(By.id("lat")).click();
    driver.findElement(By.id("lat")).sendKeys("-10");
    driver.findElement(By.id("long")).click();
    driver.findElement(By.id("long")).sendKeys("10");
    driver.findElement(By.cssSelector(".mode-section")).click();
    driver.findElement(By.cssSelector(".search-button")).click();

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".results-section > h6")));

    assertThat(driver.findElement(By.cssSelector(".results-section > h6")).getText(), is("Results for city Lagos US Embassy, Nigeria"));
    assertThat(driver.findElement(By.cssSelector("#results-pm25 > h2")).getText(), is("PM25"));
    driver.findElement(By.cssSelector("#results-pm25 > h3")).click();
    driver.findElement(By.cssSelector("#about h6")).click();
    driver.findElement(By.cssSelector(".air-title")).click();
    assertThat(driver.findElement(By.cssSelector(".result-card-cache:nth-child(1) > h2")).getText(), is("Number of Requests"));
    driver.findElement(By.cssSelector(".result-card-cache:nth-child(1) > h3")).click();
    assertThat(driver.findElement(By.cssSelector(".result-card-cache:nth-child(3) > h2")).getText(), is("Number of Misses"));
    driver.findElement(By.cssSelector(".result-card-cache:nth-child(3) > h3")).click();
  }
}
